Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace GestionAsp.Models
{
    public class Usuario
    {

        const string MAX_CARACTERES = "El usuario debe ser de 8 caracteres";

        public Usuario()
        {
            UsuariosAdministradoras = new List<UsuarioAdministradora>(3);
        }

        [Key]
        [Display(Name = "Usuario")]
        [StringLength(8, ErrorMessage = MAX_CARACTERES)]
        [Required]
        public string IdUsuario { get; set; }

        [Required, StringLength(15, ErrorMessage = "El máximo permitido son 15 caracteres"), Display(Name ="Contraseña")]
        [DataType(DataType.Password)]
        public string Contrasenia { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Apellido { get; set; }

        [EnumDataType(typeof(Nivel))]
        [Required]
        public Nivel Nivel { get; set; }


        public virtual List<Bitacora> Bitacora { get; set; }
        [Required]
        public virtual List<UsuarioAdministradora> UsuariosAdministradoras { get; set; }
    }

   
    public enum Nivel
    {
        [Required]
        Supervisor = 1,
        [Required]
        Operador = 2,
        [Required]
        Invitado = 3,
        [Required]
        Otro = 4,
        [Required]
        Administrador = 5

    }
}

Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using GestionAsp.Models;

namespace GestionAsp.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly UsuarioContext db = new UsuarioContext();

        // GET: Usuarios
        public ActionResult Index()
        {
            return View(db.Usuarios.ToList());
        }

        // GET: Usuarios/Details/5
        public ActionResult Details(string id)
        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // GET: Usuarios/Create
        public ActionResult Create()
        {
            
            List<UsuarioAdministradora> adms = new List<UsuarioAdministradora>();
            adms.Add(new UsuarioAdministradora(Administradora.Visa));
            adms.Add(new UsuarioAdministradora(Administradora.MasterCard));
            adms.Add(new UsuarioAdministradora(Administradora.Amex));
            ViewData["Administradoras"] = adms;

            List<SelectListItem> nivel = new List<SelectListItem>();

            foreach (Nivel item in Enum.GetValues(typeof(Nivel)))
            {
                nivel.Add(new SelectListItem {
                    Text = Enum.GetName(typeof(Nivel), item),
                    Value = item.ToString()
                });
            }

            ViewData["Niveles"] = nivel;


            return View();
        }

        // POST: Usuarios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdUsuario,Nombre,Apellido,Nivel,Contrasenia,UsuariosAdministradoras")] Usuario usuario)
        {
            usuario.UsuariosAdministradoras[0].Administradora = Administradora.Visa;
            usuario.UsuariosAdministradoras[1].Administradora = Administradora.MasterCard;
            usuario.UsuariosAdministradoras[2].Administradora = Administradora.Amex;

            if (ModelState.IsValid)
            {
                db.Usuarios.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdUsuario,Nombre,Apellido,Nivel")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Usuario usuario = db.Usuarios.Find(id);
            db.Usuarios.Remove(usuario);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Usuarios/Create.cshtml
@using GestionAsp.Models
@using GestionAsp.Controllers;


@*@{
    ViewBag.Title = "Alta de Usuario";
}*@

<h2>Alta de Usuario</h2>


@*@using (Html.BeginForm("Create", "Usuarios", FormMethod.Post))
{*@


<div class="form-horizontal">
    <h4>Usuario</h4>
    <hr />
    @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdUsuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdUsuario, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.Contrasenia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contrasenia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contrasenia, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>*@
    @{
        <div class="form-group">
            @Html.Label("Nivel", "Nivel", attributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Nivel",) , htmlAttributes: new { @class = "form-control" })
                @Html
            </div>
        </div>
    }



    @*<div class="form-group">
            @Html.Label("Usuario Visa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UsuariosAdministradoras[0].IdUsuarioAdm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UsuariosAdministradoras[0].IdUsuarioAdm, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="form-group">
            @Html.Label("Usuario MasterCard", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UsuariosAdministradoras[1].IdUsuarioAdm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UsuariosAdministradoras[1].IdUsuarioAdm, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="form-group">
            @Html.Label("Usuario Amex", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UsuariosAdministradoras[2].IdUsuarioAdm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UsuariosAdministradoras[2].IdUsuarioAdm, "", new { @class = "text-danger" })

            </div>
        </div>*@


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear Usuario" class="btn btn-primary" />
        </div>
        <br />

        <!-- A revisar botón Volver-->
        <!-- TODO -->
        <div class="col-md-offset-2 col-md-10">
            <input type="button" value="Volver" href="/Usuarios" class="btn btn-default" />
        </div>

    </div>
</div>
@*}*@



@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

Views/Usuarios/Delete.cshtml
@model GestionAsp.Models.Usuario

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nivel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nivel)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Usuarios/Details.cshtml
@model GestionAsp.Models.Usuario


@{
    ViewBag.Title = "Detalles del Usuario";
}

<h2>Detalles del Usuario</h2>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdUsuario)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdUsuario)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nivel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nivel)
        </dd>

        @foreach (var adm in Model.UsuariosAdministradoras)
        {
            <dt>
                @Html.DisplayFor(model => adm.Administradora)
            </dt>

            <dd>
                @Html.DisplayFor(model => adm.IdUsuarioAdm)
            </dd>

        }

    </dl>
    <hr />
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Bitacora[0].FechaAccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bitacora[0].AccionBitacora)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bitacora[0].NombreEquipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bitacora[0].Ntdom)
            </th>

        </tr>

        @foreach (var bitacora in Model.Bitacora)
        {
            <tr>
                <td>
                    @{ string fecha = bitacora.FechaAccion.ToString("dd-MM-yyyy HH:MM"); }

                    @Html.DisplayFor(modelItem => fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => bitacora.AccionBitacora)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => bitacora.NombreEquipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => bitacora.Ntdom)
                </td>

            </tr>
        }

    </table>
</div>
<p>
    @Html.ActionLink("Modificar", "Edit", new { id = Model.IdUsuario }) |
    @Html.ActionLink("Volver", "Index")
</p>

Views/Usuarios/Edit.cshtml
@model GestionAsp.Models.Usuario

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Usuario</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdUsuario)

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nivel, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Nivel, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Nivel, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Usuario Visa", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UsuariosAdministradoras[0].IdUsuarioAdm, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UsuariosAdministradoras[0].IdUsuarioAdm, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group">
        @Html.Label("Usuario MasterCard", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UsuariosAdministradoras[1].IdUsuarioAdm, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UsuariosAdministradoras[1].IdUsuarioAdm, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group">
        @Html.Label("Usuario Amex", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UsuariosAdministradoras[2].IdUsuarioAdm, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UsuariosAdministradoras[2].IdUsuarioAdm, "", new { @class = "text-danger" })

        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar Cambios" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Usuarios/Index.cshtml
@Model IEnumerable<GestionAsp.Models.Usuario>

@*@{
    ViewBag.Title = "Usuarios";
}*@

<h2>Index</h2>

<p>
   @* @Html.ActionLink("Crear Nuevo", "Create")*@
</p>
<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.IdUsuario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nivel)
        </th>
        <th>
            @Html.DisplayName("Visa")
        </th>
        <th>
            @Html.DisplayName("MasterCard")
        </th>
        <th>
            @Html.DisplayName("Amex")
        </th>*@
        <th></th>
    </tr>

@*@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.IdUsuario)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Nombre)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Apellido)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Nivel)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.UsuariosAdministradoras[0].IdUsuarioAdm)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.UsuariosAdministradoras[1].IdUsuarioAdm)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.UsuariosAdministradoras[2].IdUsuarioAdm)
    </td>
    <td>
        @Html.ActionLink("Modificar", "Edit", new { id = item.IdUsuario }) |
        @Html.ActionLink("Detalles", "Details", new { id = item.IdUsuario }) |
        @Html.ActionLink("Borrar", "Delete", new { id = item.IdUsuario })
    </td>
</tr>
}*@

</table>